### ISSUE TITLE
MT8192 kernel 6.1 LTS coverage

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1612]
Once we have Tast running with Chromium OS user-space and a reference Chrome OS kernel on MT8192 asurada, we need to enable coverage for 6.1 LTS kernel.

- [x] KernelCI YAML configuration updated to run cros-tast on 6.1 LTS kernel on MT8192 asurada
- [x] Results appear on chromeos.kernelci.org
- [x] Any issues found are either fixed or tracked on GitHub
- [x] Any extra kernel patches required on 6.1 LTS added in KernelCI
- [x] YAML configuration merged, if applicable
