### ISSUE TITLE
MT8192 kernel 6.1 ChromeOS coverage

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1613]
Once we have Tast running with Chromium OS user-space and a reference Chrome OS kernel on MT8192 asurada, we need to enable coverage for the 6.1 ChromeOS kernel.

- [ ] KernelCI YAML configuration updated to run cros-tast on 6.1 ChromeOS kernel on MT8192 asurada
- [ ] Results appear on chromeos.kernelci.org
- [ ] Any issues found are either fixed or tracked on GitHub
- [ ] Test results compared with 6.1 LTS as per #1612 
- [ ] YAML configuration merged

**Comment by gctucker** [comment]
Closing as testing ChromeOS downstream kernels on chromeos.kernelci.org is not ready yet.  This can be revisited later on when the feature becomes available.
