### ISSUE TITLE
MT8183 initial Chromium OS image

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1684]
This task is about creating an initial Chromium OS image for the MT8183 jacuzzi Chromebook.  It should include a reference Chrome OS kernel.

- [ ] Chromium OS release identified, built and tested manually
- [ ] KernelCI configuration updated to add image definition
- [ ] Image built by the KernelCI pipeline and made available on public storage
- [ ] Image flashed and tested to boot with Chromium OS in LAVA
- [ ] KernelCI configuration merged

**Comment by gctucker** [comment]
> Image flashed and tested to boot with Chromium OS in LAVA

I think this should be tweaked to mention that it's about the final image destined to be used in KernelCI and not an initial one built by hand.  I'll update #1689 accordingly.
