### ISSUE TITLE
MT8183 hardware

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1685]
There are currently 5 MT8183 jacuzzi Chromebooks in the Collabora lab:
https://lava.collabora.dev/scheduler/device_type/mt8183-kukui-jacuzzi-juniper-sku16

The goal of this task is to determine the capacity required to cover all the testing requirements and whether more devices should be sourced.

- [x] Test load estimated for KernelCI and other projects using asurada in the Collabora lab
- [x] Additional devices sourced if required
- [x] All devices are set up with Depthcharge image and pass healthchecks
- [x] All devices have the #1684 flashed on the eMMC
- [x] Device type merged upstream in LAVA
- [x] KernelCI YAML configuration entry added for running at least baseline tests

**Comment by nfraprado** [comment]
Since all work in this issue is done, I'm closing it.
