### ISSUE TITLE
MT8183 Tast enablement

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1686]
Once a Chromium OS image and a reference kernel have been provided for MT8183 as per #1684, a first set of Chrome OS Tast tests need to be enabled on this platform for chromeos.kernelci.org.

- [x] cros-baseline-fixed enabled and results appear on chromeos.kernelci.org
- [x] cros-tast-fixed enabled and results appear on chromeos.kernelci.org
- [x] Any issues are either fixed or tracked in GitHub
- [x] KernelCI YAML configuration merged

**Comment by nfraprado** [comment]
I've created an issue to track the only significant test failure on MT8183: #1960 . Though it is significant enough that I think makes sense leaving this issue open until it is fixed.

**Comment by nfraprado** [comment]
After looking into it a bit more, looks like this issue is a regression due to an update to the ChromeOS rootfs. The tests were passing before that update: https://chromeos.kernelci.org/test/plan/id/645d08387b7495b13e748108/ . So that issue will be tracked and resolved separately, and I'm closing this issue.
