### ISSUE TITLE
MT8195 initial Chromium OS image

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1689]
This task is about creating an initial Chromium OS image for the MT8195 cherry Chromebook.  It should include a reference Chrome OS kernel.

- [ ] Chromium OS release identified, built and tested manually
- [ ] KernelCI configuration updated to add image definition
- [ ] Image built by the KernelCI pipeline and made available on public storage
- [ ] Image flashed and tested to boot with Chromium OS in LAVA
- [ ] KernelCI configuration merged
