### ISSUE TITLE
MT8195 hardware

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1690]
There are currently no MT8195 cherry Chromebooks in the Collabora lab.  A minimum of 5 is typically required to run KernelCI tests.

The goal of this task is to determine the capacity required to cover all the testing requirements and whether more devices should be sourced.

- [x] Test load estimated for KernelCI and other projects using cherry in the Collabora lab
- [x] Additional devices sourced if required
- [ ] All devices are set up with Depthcharge image and pass healthchecks
- [ ] All devices have the #1608 flashed on the eMMC
- [x] Device type merged upstream in LAVA
- [ ] KernelCI YAML configuration entry added for running at least baseline tests

**Comment by laura-nao** [comment]
Enablement of `cherry` (codename `tomato`) in the lab is in progress; we have 7 devices operational in the Collabora LAVA lab (custom Depthcharge image flashed; passing LAVA health checks), 5 more units left to be added.

Documentation for the specific model we have in the lab: https://lava.pages.collabora.com/docs/boards/chromebooks/boards/cherry

LAVA device type template has been merged upstream: https://git.lavasoftware.org/lava/lava/-/blob/master/etc/dispatcher-config/device-types/mt8195-cherry-tomato-r2.jinja2

**Comment by nuclearcat** [comment]
Closing as not planned following #3196, which retires ChromeOS-specific build and test coverage. If generic Linux support for this Chromebook hardware is still needed, please open a newly scoped issue.
