### ISSUE TITLE
MT8195 Tast enablement

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1691]
Once a Chromium OS image and a reference kernel have been provided for MT8195 as per #1689, a first set of Chrome OS Tast tests need to be enabled on this platform for chromeos.kernelci.org.

- [ ] cros-baseline-fixed enabled and results appear on chromeos.kernelci.org
- [ ] cros-tast-fixed enabled and results appear on chromeos.kernelci.org
- [ ] Any issues are either fixed or tracked in GitHub
- [ ] KernelCI YAML configuration merged

**Comment by nuclearcat** [comment]
Closing as not planned following #3196. KernelCI is retiring ChromeOS-specific coverage and the Tast integration this issue was intended to enable.
