### ISSUE TITLE
MT8195 kernel 6.1 LTS coverage

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#1692]
Once we have Tast running with Chromium OS user-space and a reference Chrome OS kernel on MT8195 cherry, we need to enable coverage for 6.1 LTS kernel.

- [ ] KernelCI YAML configuration updated to run cros-tast on 6.1 LTS kernel on MT8195 cherry
- [ ] Results appear on chromeos.kernelci.org
- [ ] Any issues found are either fixed or tracked on GitHub
- [ ] Any extra kernel patches required on 6.1 LTS added in KernelCI
- [ ] YAML configuration merged, if applicable

**Comment by gctucker** [comment]
Note: Full upstream kernel support is expected to land in 6.3, so it's very likely that Tast tests or even baseline won't work at all on 6.1.  We might add a few patches on top of 6.1 LTS for chromeos.kernelci.org if the device tree is incomplete or minor code changes.  Depending on the amount of kernel tweaks, we might have to decide to not enable 6.1 tests on MT8195 cherry and pick newer stable branches such as 6.3 until the following LTS is available (e.g. 6.5?) at the end of 2023.

**Comment by nuclearcat** [comment]
Closing as not planned following #3196. The ChromeOS/Tast coverage targeted here is being retired, and the requested 6.1 LTS enablement is no longer on the project roadmap.
