### ISSUE TITLE
Investigate `click` and `typer`

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#2110]
The current `kci` command line tool is based on the same code as in the legacy tools `kci_build`, `kci_test` etc.  As part of needing a redesign, it's worth considering alternative packages such as [`click`](https://click.palletsprojects.com/) and [`typer`](https://typer.tiangolo.com/) (which is based on `click`).

Investigating whether we can use them and comparing them can be done by implementing the basic support for loading settings values from TOML for the current command, looking up TOML settings groups based on a config name (e.g. to find an API token for a particular API instance config), implementing some dummy nested commands as well as a real `whoami` command as a proof-of-concept.

- [x] Initial investigation of `click` #2111 
- [x] Initial investigation of `typer` #2112 
- [x] Summary and comparison
- [x] Discussed with users and community
- [x] Follow-up plan described on GitHub #2125
