### ISSUE TITLE
kselftest

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#331]
[kselftest](https://www.kernel.org/doc/html/latest/dev-tools/kselftest.html) is one of the main test suites that comes with the Linux kernel itself.  As such, it is an obvious one to cover on kernelci.org.  Doing so poses a few challenges, as it needs changes to the build system to build the tests from the kernel tree for each revision being tested and then install them on the target platform to run them.

- [x] #339 basic plumbing to get kselftest builds
- [x] #487 initial runtime coverage in LAVA labs
- [x] #499 first pass at getting as many tests to build
- [x] #636 fine-tuning of the build environment to separate kselftest errors from main kernel build errors
- [x] #655 first pass at fixing runtime dependencies

**Comment by kees** [comment]
Can the kselftest tarball be included in the build artifacts?

`make -C tools/testing/selftests gen_tar FORMAT=.xz`

**Comment by kees** [comment]
Oh, I see https://github.com/kernelci/kernelci-core/pull/339 already exists. :)

**Comment by gctucker** [comment]
Yes, it's not enabled in production yet though but should get there soon as the PR you found is functional.

**Comment by alexandrasp** [comment]
After check and try to improve kselftest in kernel-ci build we decided to split missing selftests errors in little tasks because they are more complicated or are not related to just installing some package.
 
The new summary is:

- [ ] Fix problems related to reader files not found in kselftest builds
- [ ] Fix bpftool error with missing vmlinux
- [ ] Fix bpf kselftest build issue due to missing numa.h
- [ ] Build with success: filesystems/binderfs, exec, kvm and pidfd selftests.

**Comment by alexandrasp** [comment]
And a brief update, after changes #531, #528 and #525
The list of extra directories that we have started to build with gcc are:

On arm64:

Skipping non-existent dir: exec
+Emit Tests for filesystems/binderfs
Skipping non-existent dir: kexec
+Emit Tests for kvm
+Emit Tests for pidfd
Skipping non-existent dir: tc-testing
Skipping non-existent dir: vm

On x86_64:

Skipping non-existent dir: exec
+Emit Tests for filesystems/binderfs
Skipping non-existent dir: kexec
+Emit Tests for kvm
+Emit Tests for pidfd
Skipping non-existent dir: tc-testing
+Emit Tests for vm

On arm:

Skipping non-existent dir: exec
+Emit Tests for filesystems/binderfs
Skipping non-existent dir: kexec
Skipping non-existent dir: kvm
+Emit Tests for pidfd
Skipping non-existent dir: tc-testing
Skipping non-existent dir: vm

**Comment by gctucker** [comment]
Some kselftest collections have now been enabled in production, here are a few sample results on mainline:
* https://linux.kernelci.org/test/plan/id/60a4286471ac53568db3afb4/ `kselftest-filesystems` on x86
* https://staging.kernelci.org/test/plan/id/60a30a8b91fd0e2761212bc6/ `kselftest-lib` on arm
* https://staging.kernelci.org/test/plan/id/60a3171f64c30ab53c212b9f/ `kselftest-futex` on arm64
