### ISSUE TITLE
Initial kci_data implementation

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#407]
One missing piece in the KernelCI core tools is the ability to submit test results.  While kci_build can upload kernel build meta-data and binaries, and kernelci-backend has a callback handler for LAVA labs, there is no solution for other tests than to use a custom tool or `curl` with a JSON file.

The first step is to have a `kci_data` tool which can be used to submit test results to the kernelci-backend API.  It will need to be designed with an abstract class interface like for the test labs, so that other backends can be added later (in particular, KCIDB).

- [x] #409 YAML configuration implemented in `kernelci.config.data`, for `db-configs.yaml`
- [x] database interface defined in `kernelci.data.Database()` class #435 
- [x] kernelci-backend implementation in `kernelci.data.kernelci_backend.KernelCIBackend()` #435
- [x] #409 Only sending test results needs to be implemented at this stage.

Note: Tokens are still passed on the command line only until we can have a config file for them.

The code to send kernel build meta-data currently used by `kci_build` should be moved to `kernelci.data`, but this can be done as a follow-up task.

**Comment by gctucker** [comment]
This is a bit late now, we should resolve it at the beginning of next week.

**Comment by mgalka** [comment]
Aren't these bullet points also done in #409 ?
- backend interface defined in kernelci.data.Database() class
- kernelci-backend API implementation in kernelci.data.backend.Backend()

**Comment by gctucker** [comment]
Kind of, there's an implementation but it's not object-oriented with an abstract interface base class.  So it's OK for the scope of that initial PR, but not strictly what is being described in this issue.

**Comment by gctucker** [comment]
Here's a Gist to discuss how the tool would work:
https://gist.github.com/gctucker/46e704ddbffa2ee806ec8793ff144449
