### ISSUE TITLE
libcamera and lc-compliance

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-core#685]
There is a new test suite as part of libcamera called [lc-compliance](https://git.linuxtv.org/libcamera.git/tree/src/lc-compliance) which would be very interesting to enable on KernelCI as described on the [mailing list](https://groups.io/g/kernelci/topic/resend_running_libcamera_on/82986127).

This may reuse the existing buster-v4l2 rootfs image or require a new one.  The test suite needs to be compiled from source and integrated with the rootfs in a similar way.

Some hardware available in Collabora's LAVA lab is suitable to run this test, with real camera devices.  It may also be used with virtual devices and QEMU.

- [x] #695 Submit LAVA job by hand to run lc-compliance
- [x]  #704 add lc-compliance rootfs
- [x] #720 add lc-compliance test

**Comment by gctucker** [comment]
This is now all done :)
